[project]
title = "Signl"
version = "0.1.0"
port = 8501
slug = "preswald-project-908628"  
entrypoint = "hello.py"    

[branding]
name = "signl"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#E9EDC9"

[data.health_activity_data_csv]
type = "csv"
path = "data/health_activity_data.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"